#!/usr/bin/env ruby

#
# This script will get the output generated by nodeset and it will create a symlink to a file passed as argument on the cmd line.
#
# Usage: nodeset --expand node[1-4].mydomain | ruby create_symlink.rb -f /some/file
#
require "optparse"
require "resolv"

options = {}

OptionParser.new do |parser|
  parser.on("-f", "--file NAME", "The name of the file which the symlink should point to.") do |v|
    options[:filename] = v
  end
end.parse!

# Enforce the presence of the cmd line option:
begin
  mandatory = [:filename]
  missing = mandatory.select{ |param| options[param].nil? }
  unless missing.empty?
    raise OptionParser::MissingArgument.new(missing.join(', '))
  end
rescue OptionParser::InvalidOption, OptionParser::MissingArgument
  puts $!.to_s
  exit(1)
end

# Read the output produced by nodeset and create the symlinks:
if ARGF.filename != "-" or (not STDIN.tty? and not STDIN.closed?) # Are we not reading input from STDIN?
  ARGF.each do |line|
    hostnames = line.split(" ")
    hostnames.each do |hostname|
      begin
        address = Resolv.getaddress(hostname)
        File.symlink(options[:filename], address)
      rescue Resolv::ResolvError
        puts "#{hostname} has no IP address associated."
      end
    end
  end
else
  puts "No feeding from STDIN."
  exit(1)
end

